sudo: false
language: node_js
node_js:
- '5.0'
cache:
  directories:
  - node_modules
install:
- npm install
env:
  global:
  - GH_USERNAME: Travis CI
  - GH_EMAIL: todvora@gmail.com
  - GH_REF: github.com/todvora/gh-events-widget.git
  - secure: Q35UUK7xEHpcHvdPVj1oa9Yv9InkAivbsgvOsRtN9CYgDVNDa4KkzQXLSDhlTLc12gSYe1JrXBx3ohSZuxSksJ6zPFYo5tjzLk672RBy/8bnIM942LeE82osfaNiyPEroq+Wk8NO/1sP5Lt+/SaJaXtaqHIXdTvQBKRT++7YdB7a4WjJU8VLtT5TGXYqZK3mANipY9+JIT0md/BFofGO6nBjy2K4KQ4E/lpo23CnWwtmD+JF0EhwwzgrglrWCu8ibbj31G0J4m5ZzZBEZQ18Js1zQ1shG2yhRYhWXlfp2TyCvkWgdd7s8eY3WSDe0ZX4yPTj7I2LljmhSQe3b6X0X3/qagxo2frthyWUKp/7w2MtZL8/9TZfKMz+Gog8lfh0gWIpfEXC9g1VI/oehaHW4WOWAyklV/NPoeimLl/EXTulrFqymsuLeG2OPWi5NBDsN1CLvD+Z7wJlEQPUJSpELVLE2dq74z8S2l40gcAW+DD8RM+PAFnUabCmcjZeCLYcQBMrUTyQQ42N/kdU8wungZTVfX+6op2msogzvGGk558TFfsv0noU2WeGoSvqzyrTWiZKaXtVe5R8lw4kELLQIwnrFdFUKDqRRjbvcxGfoHYA7JUwpdVItzz5P3+u9wVB/jvpKtz1Gt1YqFi5NNh63+T2Tj/J6+ZT07+lRGLcZUY=
script:
- npm test

deploy:
  skip_cleanup: true
  provider: script
  script: npm run distribute
